const CREATE_TODO = 'CREATE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const FETCH_TODO = 'FETCH_TODO';

export { CREATE_TODO, DELETE_TODO, UPDATE_TODO, FETCH_TODO };
